#version: '3.8'

services:
  server1:
    image: nginx:latest
    container_name: nginx_server01
    ports:
      - "8081:80"
    volumes:
      - ./server01:/usr/share/nginx/html
    networks:
      - loadbalancer_network

  server2:
    image: nginx:latest
    container_name: nginx_server02
    ports:
      - "8082:80"
    volumes:
      - ./server02:/usr/share/nginx/html
    networks:
      - loadbalancer_network

networks:
  loadbalancer_network:
    driver: bridge
